### ISSUE TITLE
Documentation enhancement: Add references section

### ISSUE THREAD

**Issue by rsasaki0109** [TakumaNakao/mathematical_robotics#1]
@TakumaNakao 
Hi there,

Thank you for sharing such wonderful code!

I noticed that the documentation is missing a list of references or sources that were used to gather the information presented. 
Would it be possible to include a list of references or sources in the documentation? This would be especially helpful for users who want to dive deeper into the topic and explore additional information.

Thank you for considering this request.

**Comment by rsasaki0109** [comment]
The reason I'm raising this issue is because when I introduced your OSS on X, I received [a comment from a user.](https://x.com/scomup/status/1719979957466923136?s=20) 
 He mentioned that if this OSS is inspired by[ MathematicalRobotics](https://github.com/scomup/MathematicalRobotics), he would appreciate it if it could be added to the references.

**Comment by TakumaNakao** [comment]
Thanks for pointing that out.
I added the references.
And thank you for referring to my repository.
